### PR TITLE
DOCS: improve shopyo setup instructions

### LINKED ISSUE #52: DOCS: fix the setup instructions login link
Fix step 13 of `Setup Instructions` section in [`contrib.rst`](https://github.com/shopyo/shopyo/blob/dev/docs/contrib.rst#setup-instructions) by changing http://localhost:5000/login/ to http://localhost:5000/auth/login

### PR DESCRIPTION
**Pull request by rehmanis**
* follow the pattern for contribution that Flask uses

fixes #52

### CODE REVIEW

**Comment by rehmanis** [comment]
@mahgieeee would you like to review the docs changes I made for this PR ? Only if you have time. Just need to check the [contribution guide](https://shopyo--60.org.readthedocs.build/en/60/contrib.html) (make sure to refresh your browser cache to view the newest doc version) and see for mistakes or any other suggestions. You can directly start a review by clicking [Files Changed](https://github.com/shopyo/shopyo/pull/60/files) and making comments. See this [guide](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) for how to review.

**Comment by mahgieeee** [comment]
@rehmanis hi! most certainly, I can do this tomorrow morning. Sorry been busy these couple of days, but I can work on it and let you know thanks!

**Comment by rehmanis** [comment]
> @rehmanis hi! most certainly, I can do this tomorrow morning. Sorry been busy these couple of days, but I can work on it and let you know thanks!

@mahgieeee yeah no rush. Just wanted someone to have look and and also gives you contribution points for reviewing.

**Comment by rehmanis** [comment]
@mahgieeee just checking in. I can merge if you don't have time to review.

**Pull request merged**
