### PR TITLE
Added error logs in app.py

### LINKED ISSUE #122: BUG: Fix error not shown upon global load
Print error in these cases: 

https://github.com/shopyo/shopyo/blob/eb927cf223a1441df8fe3b98b427b168fffa403e/shopyo/app.py#L170

https://github.com/shopyo/shopyo/blob/eb927cf223a1441df8fe3b98b427b168fffa403e/shopyo/app.py#L204

In the format:

```
print('[ ] error loading template variable', e)
```

For all errors

### PR DESCRIPTION
**Pull request by sanmay321**
added print('[ ] error loading template variable', e) in line 176 and 210 , 
this PR resolves #122

### CODE REVIEW

**Comment by sanmay321** [comment]
@Abdur-rahmaanJ hey I have made the necessary changes mentioned in the issue, please review the changes and let me know if there is something else to add or change, Thank you!

**Review by Abdur-rahmaanJ — CHANGES_REQUESTED** [review]
Great, do so for the other errors :+1:

**Comment by sanmay321** [comment]
@Abdur-rahmaanJ Could you please help me with this error? Actually, it's my first time dealing with this error, so I don't know what to do.

**Comment by Abdur-rahmaanJ** [comment]
@sanmay321 for this

```
except AttributeError:
                    pass
```

**Pull request closed without merging**
