### PR TITLE
docs: createmodule

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ we don't have createmodule command.

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ see https://github.com/shopyo/shopyo/blob/dev/CHANGES.md

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis in 4.1.2 we have it, just checked. Until we push to pypi it must remain

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ I see. Keep the usage consistent (same as other cmds). See https://github.com/shopyo/shopyo/blob/08c982e4c150d927d63070a0957f2103eac3d443/docs/commandline.rst#createmodule

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis i was getting errors with this one:

```
shopyo createmodule box__plate/dumpling # modules/box__plate/dumpling
```

That's why i put it as i put

**Comment by rehmanis** [comment]
I meant this part:
```
shopyo createmodule [OPTIONS] MODULENAME [BOXNAME]
```
or 

```
python manage.py createmodule [OPTIONS] MODULENAME [BOXNAME]
```

**Pull request merged**
