### PR TITLE
[#94]: Add filtering options to the audit command

### LINKED ISSUE #94: Add filtering options to the audit command
shopyo audit generates something like this:

```
Running audit ...
Checking apps ...
/home/appinv/code/shopyo/shopyo/modules/www
    warning: global.py not found

/home/appinv/code/shopyo/shopyo/modules/resource
    warning: global.py not found

/home/appinv/code/shopyo/shopyo/modules/box__default
    /home/appinv/code/shopyo/shopyo/modules/box__default/settings
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/dashboard
        warning: forms.py not found
        warning: models.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/auth
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/appadmin
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/base
        warning: forms.py not found
        warning: models.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/theme

/home/appinv/code/shopyo/shopyo/modules/box__bizhelp
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/people
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/appointment
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/contact
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/page
        warning: global.py not found

Audit finished!

```

The command is defined [here](https://github.com/shopyo/shopyo/blob/2aa4cf467a6ead735578667b242bec9803d070b5/shopyo/api/cli.py#L511) with the audit [here](https://github.com/shopyo/shopyo/blob/2aa4cf467a6ead735578667b242bec9803d070b5/shopyo/api/cmd_helper.py#L451).

It is cumbersome to view all warnings. We can add flags to filter warnings by severe like --show severe,warning

Task: Add flags to filter warnings. Feel free to modify the code!

### PR DESCRIPTION
**Pull request by gsinghly**
fixes #94

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@gsinghly Very elegent!!!

**Comment by Abdur-rahmaanJ** [comment]
@gsinghly can i merge?

**Comment by gsinghly** [comment]
@Abdur-rahmaanJ , yes please review and merge. Thanks!

**Review by Abdur-rahmaanJ — APPROVED** [review]
- The pre-commit checks failed (you used pre-commit ?)
- Repeating .split might have been in a function

Else good!

**Comment by gsinghly** [comment]
yes, used pre-commit, not sure why it failed here, on my local dev the test passed, added screenshot, 
Screenshot 2022-09-03 at 3 10 42 AM

for `Repeating .split might have been in a function`, yes, thanks would fix that sometime.

**Pull request merged**
