### PR TITLE
Theme change to Furo

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis zero idea why fail

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ  what is the point of merging when all tests are failing?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis Maybe we should document what we are testing also

**Comment by rehmanis** [comment]
If you see the actions tace out, it say for example `Click 8.0.0` , `Werkzeug 2.0.0` etc which are the latest releases. That is why it is failing.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis ok we were not freezing. Did you ever try pipenv or such tools?

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ I haven't.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis for the time being we can pip freeze. Give me till tomorrow i'll put the results

**Pull request merged**
