### PR TITLE
Add contributing link

### PR DESCRIPTION
**Pull request by lokeshvasnik**
Replaced the contributing link with a new one

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@lokeshvasnik Please sign the cla ^^

**Comment by lokeshvasnik** [comment]
that's it?

**Comment by Abdur-rahmaanJ** [comment]
@lokeshvasnik 

:heavy_check_mark: Well done!
:100: Merging!

**Comment by lokeshvasnik** [comment]
If you have any front end tasks feel free to contact

**Comment by Abdur-rahmaanJ** [comment]
@lokeshvasnik Ok will do ^^

**Comment by lokeshvasnik** [comment]
Great thankyou

**Comment by Abdur-rahmaanJ** [comment]
@lokeshvasnik Join [the discord](https://discord.gg/k37Ef6w) If you want some chats

**Pull request merged**
